# http-Server Configuration
server:
  port: ":5090"
  url: localhost
  write_timeout: 15s       # seconds
  read_timeout: 15s 
  idle_timeout: 60s 
  shutdown_delay: 5s 
  readbuffer_size: 1024   # bytes
  writebuffer_size: 1024  # bytes
  log:
    level: debug        # [debug | info | warn | error] 
    format: json        # [json | text]
    log_file: nexIOserver.log

client:
  url: ws://localhost:5090/ws
  pong_wait: 60s        # seconds
  write_deadline: 10s   
  max_backoff: 32s 
  ctx_timeout: 5s
  max_messagesize: 512  # bytes
  log:
    level: info        # [debug | info | warn | error] 
    format: json       # [json | text]
    log_file: nexIOclient.log
  auth:
    user: admin
    secret: default-secret # do NOT in production use ENV [ GSF_CLIENT_AUTH_SECRET ] instead
    
# RPC Messaging
protocol:
  pong_wait: 60        # seconds
  #ping_period  = 90% von pong
  write_deadline: 10    # seconds
  max_messagesize: 512  # bytes
  max_backoff: 30       # seconds


